name: NPM Install Dynamic Node

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version:
        description: "Node.js version (e.g. 16, 18, 20)"
        required: false
        options:
          - "16"
          - "18"
          - "20"

jobs:
  npm-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set NVMRC
        if: github.event_name == 'workflow_dispatch'
        id: set-node-version
        run: |
          if [ -n "$NVMRC_VALUE" ]; then
            echo "{node_version}={$(echo $NVMRC_VALUE | sed 's/^v//')}" >> $GITHUB_ENV
          else
            echo "{node_version}={$(cat .nvmrc | sed 's/^v//')}" >> $GITHUB_ENV
          fi
        env:
          NVMRC_VALUE: ${{ github.event.inputs.node_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Run npm ci with the specified Node.js version
        run: |
          echo "Running npm ci with Node.js version: ${{ env.node_version }}"
          npm ci
