name: NPM Install Dynamic Node

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version:
        description: "Node.js version (e.g. v16, v18, v20)"
        required: false

jobs:
  npm-install:
    runs-on: ubuntu-latest

    steps:
      - id: step1
        run: echo "name=hello" >> $GITHUB_OUTPUT
    
      - id: step2
        run: echo "name=test::world" >> $GITHUB_OUTPUT
    
      - name: Display
        run: |
          echo "Step 1 test: ${{ steps.step1.outputs.test }}"
          echo "Step 2 test: ${{ steps.step1.outputs.test }}"
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set NVMRC
        if: github.event_name == 'workflow_dispatch'
        id: set-node-version
        run: |
          if [ -n "$NVMRC_VALUE" ]; then
            echo "{node_version}={$(echo $NVMRC_VALUE)}" >> $GITHUB_ENV
          else
            echo "{node_version}={$(cat .nvmrc)}" >> $GITHUB_ENV
          fi
        env:
          NVMRC_VALUE: ${{ github.event.inputs.node_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}

      - name: Run npm ci with the specified Node.js version
        run: |
          echo "${{ env.node_version }}"
          echo "Running npm ci with Node.js version: $env ${{ env.node_version }} {node_version} $NODE_VERSION {env.node_version}"
          npm ci
